# How a Drone Works

## Overview
The heart of a drone’s operation is based on Newton’s Third Law of Motion:

> For every action, there is an equal and opposite reaction.

Drone propellers push air downwards, which generates an upward force (lift). This lift allows drones to:
- Hover
- Ascend
- Descend

By adjusting the speed of the propellers, drones can precisely control their movement.

---

## Forces Acting on a Drone

To maintain stable flight, several forces must be balanced:

1. Propulsion Force  
   - Generated by spinning propellers  
   - Pushes air downward to create lift  

2. Weight (Gravity)  
   - Downward force acting on the drone  
   - Formula: Fg = mg  

3. Drag  
   - Air resistance opposing motion  

4. Lift  
   - Upward force generated by propellers  
   - Counteracts gravity  

5. Thrust  
   - Forward or horizontal force when the drone tilts  

Stable flight occurs when these forces are balanced, controlled by onboard systems.

---

## Propeller Mechanics

- Lift depends on:
  - Rotational speed
  - Blade angle (pitch)

- Larger or faster-spinning propellers produce more lift  
- This allows drones to carry heavier payloads  

---

## Drone Stability

Drone stability is achieved using:

- Gyroscopes  
- Accelerometers  

These sensors:
- Detect orientation and movement  
- Send data to the flight controller  

The flight controller adjusts motor speeds in real-time to maintain balance.

---

## Drone Movements (Axes)

Drones move in three primary ways:

### Yaw
- Rotation around the vertical axis  
- Turns drone left or right  

### Pitch
- Tilts forward/backward  
- Enables forward or backward movement  

### Roll
- Tilts sideways  
- Enables left or right movement  

---

## Torque and Rotation Control

- Adjacent propellers spin in opposite directions  
- This cancels out unwanted torque  

Yaw control:
- Speed up two propellers in one direction  
- Slow down the other two  
- Creates rotational motion  

---

## Flight Controller

The flight controller is the brain of the drone.

It:
- Processes data from sensors:
  - Accelerometers  
  - Gyroscopes  
  - Magnetometers  
  - GPS  
- Adjusts motor speeds  
- Stabilizes flight  
- Executes pilot or autonomous commands  

---

## Main Components of a Drone

### Airframe
- Structural body of the drone  
- Holds all components together  

### Motors
- Spin the propellers  
- Typically brushless DC motors  
- Efficient and low maintenance  

### Propellers
- Generate lift by moving air  
- Affect stability, speed, and efficiency  

Example:
8" x 4.5"  
- 8 inches = length  
- 4.5 inches = pitch (distance traveled per rotation)  

---

### Electronic Speed Controllers (ESC)
- Regulate motor speed  
- Receive signals from the flight controller  
- Each arm of the drone has one ESC  

---

### Battery (Li-Po)
- High energy density  
- Determines:
  - Flight time  
  - Power output  

---

### GPS Module
- Enables:
  - Position tracking  
  - Autonomous flight  
  - Return-to-home (RTH)  

---

### Sensors
Provide critical flight data:
- Barometer → altitude  
- Magnetometer → direction  
- IMU → motion/orientation  
- Visual sensors → obstacle avoidance  

---

## Summary

A drone flies by:
- Generating lift through propellers  
- Balancing forces (lift, weight, drag, thrust)  
- Using sensors for stability  
- Adjusting motor speeds via a flight controller  

---

## Key Takeaway

A drone is a finely balanced system where physics, electronics, and software work together to achieve stable and controlled flight.
